name: RiseArea
description: Mobile platform that uses gamification to empower entrepreuners.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  timer_builder: ^1.3.0
  shimmer: ^1.1.0
  gradient_app_bar: ^0.1.3
  flip_card: ^0.4.4
  provider: 
  slimy_card:
  simple_animations: ^1.3.4
  flutter_screenutil: ^1.0.2
  font_awesome_flutter: ^8.5.0
  flutter_staggered_animations: "^0.1.2"
  curved_navigation_bar:
  clay_containers:
  custom_switch: 
    git: 
      url: https://github.com/MarcioQuimbundo/custom_switch_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/profile_pic.png
    - assets/next_profile.png
    - assets/coin.png
    - assets/calculator.png
    - assets/cloud.png
    - assets/curso.png
    - assets/party.png
    - assets/playbutton.png
    - assets/sword.png
    - assets/book.png
    - images/1.jpg
    - images/rocket1.png
    - images/rocket2.png
    - images/rocket.png
    - images/rocket3.png
    - images/rocket4.png
    - images/beneficios-aws.jpg
    - images/beneficios-trello.jpg
    - images/beneficios-contaazul.jpg


  fonts:
    - family: BastardusSans
      fonts:
        - asset: assets/fonts/BastardusSans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: BellotaText
      fonts:
        - asset: assets/fonts/BellotaText-Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
